plugins {
    id 'java'
    id "me.champeau.jmh" version "0.7.2"
    id("io.freefair.lombok") version "8.10"
    id 'maven-publish'
}

group = 'io.ib67'
version = '0.1.1'

/**
 * -XX:+UnlockDiagnosticVMOptions
 -Xlog:class+load=info
 -XX:+LogCompilation
 */
jmh {
    warmupIterations = 2
    iterations = 2
    fork = 1
    threads = 1
    jvm = "/home/icybear/fastdebug/jdk/bin/java"
    if (System.getenv("CI") == null) {
//        profilers = ['jfr:dir=profile-results']
        jvmArgsPrepend = ["-fastdebug"]
        jvmArgsAppend = ["-XX:+UnlockDiagnosticVMOptions", "-XX:LogFile=jitlog.log", "-XX:+PrintAssembly", "-XX:+DebugNonSafepoints", "-Xlog:class+load=info", "-XX:+LogCompilation"]
    } else {
        fork = 2
        iterations = 3
    }
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = targetCompatibility = 21
    withSourcesJar()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.awaitility:awaitility:4.2.2'
    compileOnly 'org.jetbrains:annotations:25.0.0'
}
publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'buz'
            version = version

            from components.java
        }
    }
}
test {
    useJUnitPlatform()
}